name: unity-meta-file-check (github-hosted ubuntu-latest)
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - src/Utils.Unity/Assets/**
      - src/Utils.Unity/Packages/**
  workflow_dispatch: {}

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          submodules: false
          lfs: true
      - name: Unity meta files check (github-hosted ubuntu-latest)
        uses: DeNA/unity-meta-check@v4
        with:
          target_path: src/Utils.Unity
